export const wizardCopy = {
  screen1: {
    nameLabel: 'Wie dürfen wir dich ansprechen?',
    namePlaceholder: 'Vorname oder Spitzname',
    nameHelper: 'Nur dein Vorname reicht',
    emailLabel: 'Deine E-Mail für die Therapievorschläge',
    emailPlaceholder: 'deine@email.de',
    emailHelper: 'Wir schicken dir passende Therapeut:innen',
    cta: 'Passende Therapeut:innen finden →',
  },
  screen2: {
    header: 'Lass uns die perfekte Unterstützung für dich finden',
    startLabel: 'Wann möchtest du starten?',
    startOptions: ['Diese Woche (Akutplätze verfügbar)', 'Innerhalb eines Monats', 'Bin flexibel'] as const,
    kassentherapieLabel: 'Hast du bereits eine Kassentherapie gemacht?',
    kassentherapieOptions: ['Ja, abgeschlossen', 'Ja, bin noch in Therapie', 'Nein', 'Bin mir nicht sicher'] as const,
    kassentherapieArt: 'Welche Art von Therapie war/ist es?',
    kassentherapieArtOptions: [
      'Verhaltenstherapie (CBT)',
      'Tiefenpsychologische Therapie',
      'Psychoanalyse',
      'Systemische Therapie',
      'Andere',
      'Weiß ich nicht',
    ] as const,
    whatMissing: 'Was fehlt dir noch?',
    whatMissingOptions: [
      'Ich verstehe alles, aber kann es nicht ändern',
      'Möchte mit Körperempfindungen arbeiten',
      'Brauche einen anderen Ansatz',
      'Suche traumasensible Begleitung',
      'Andere Gründe',
    ] as const,
    next: 'Weiter →',
  },
  screen3: {
    header: 'Fast geschafft - noch ein paar praktische Details',
    whereLabel: 'Wo suchst du Unterstützung?',
    cityLabel: 'Stadt',
    onlineOk: 'Online-Therapie ist auch okay',
    budgetLabel: 'Wie viel kannst du pro Sitzung investieren?',
    budgetOptions: ['Unter 80€', '80-120€', 'Über 120€', 'Brauche einen Zahlungsplan'] as const,
    budgetHelper: 'Steuerlich absetzbar als außergewöhnliche Belastung',
    privacyLabel: 'Ist dir Privatsphäre wichtig?',
    privacyHelper: 'Keine Krankenkassen-Akten, keine Diagnosen',
    privacyOptions: ['Ja, sehr wichtig', 'Nein, ist mir egal', 'Bin mir unsicher'] as const,
    next: 'Weiter →',
  },
  screen4: {
    header: 'Letzte Details für deine perfekte Vermittlung',
    genderLabel: 'Bevorzugtes Geschlecht der Therapeut:in',
    genderOptions: ['Frau', 'Mann', 'Keine Präferenz', 'Divers/non-binär'] as const,
    languageLabel: 'In welcher Sprache möchtest du Therapie machen?',
    languageOptions: ['Deutsch', 'Englisch'] as const,
    languageOther: 'Andere',
    timeLabel: 'Wann hast du Zeit für Termine? (Mehrfachauswahl)',
    timeOptions: ['Morgens (8-12 Uhr)', 'Nachmittags (12-17 Uhr)', 'Abends (17-21 Uhr)', 'Wochenende', 'Bin flexibel'] as const,
    methodsLabel: 'Interessierst du dich für bestimmte Methoden? (Optional)',
    methodsOptions: ['NARM (Entwicklungstrauma)', 'Somatic Experiencing', 'Core Energetics', 'Hakomi', 'Bin offen für Vorschläge'] as const,
    methodsHelper: 'Nicht sicher? Wir helfen dir bei der Auswahl',
    next: 'Weiter →',
  },
  screen5: {
    header: 'Gibt es noch etwas, was wir wissen sollten?',
    infoLabel: 'Z.B. spezielle Themen, Zeitdruck, oder andere Wünsche',
    submit: 'Anfrage abschicken →',
  },
  screen6: {
    header: '✓ Geschafft! Deine Anfrage ist bei uns',
    body1: 'Hallo {name},',
    body2: 'Konstantin prüft persönlich deine Anfrage und sucht die besten Therapeut:innen für dich.',
    body3: 'Du bekommst deine Matches innerhalb von 24 Stunden.',
    important: 'Wichtig: Bitte bestätige deine E-Mail-Adresse, damit wir dir deine Matches schicken können.',
    checkEmail: 'E-Mail wurde gesendet – jetzt checken',
    helper: 'Keine E-Mail bekommen? Check deinen Spam-Ordner oder klick hier für neuen Versand',
  },
};

export const PROGRESS_STEPS = [0, 20, 50, 75, 90, 100] as const;
